version: "3"

services:
    meilisearch:
        image: getmeili/meilisearch:v1.14
        container_name: geektime-meilisearch
        ports:
            - ${MEILISEARCH_PORT:-7700}:7700
        environment:
            - MEILI_ENV=${MEILI_ENV:-development}
            - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-geektime-search-master-key}
        volumes:
            - ./meili_data:/meili_data
        restart: unless-stopped

    webserver:
        image: python:3.12-slim
        container_name: geektime-webserver
        ports:
            - ${WEB_PORT:-8000}:8000
        volumes:
            - ./:/app
        working_dir: /app
        command: python -m http.server 8000
        depends_on:
            - meilisearch
        restart: unless-stopped
